CREATE TABLE IF NOT EXISTS book (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    number BIGINT NOT NULL DEFAULT 1,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE book
    ADD COLUMN IF NOT EXISTS number BIGINT NOT NULL DEFAULT 1;

ALTER TABLE book
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE book
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS operation_history (
    id BIGSERIAL PRIMARY KEY,
    operation_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(120) NOT NULL,
    operator_name VARCHAR(120),
    entity_name VARCHAR(255),
    detail TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS operation_type VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS entity_type VARCHAR(120) NOT NULL DEFAULT 'Unknown';

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS operator_name VARCHAR(120);

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS entity_name VARCHAR(255);

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS detail TEXT;

ALTER TABLE operation_history
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;